server:
   port: 8080 #修改端口号
eureka:
   instance:
      hostname: localhost #eureka服务端起个名字
   client:
      registerWithEureka: false #由于自己就是服务器，不需要注册到自己
      fetchRegistry: false #是否检索服务
      serviceUrl:
         defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #注册中心的地址
spring:
   application:
      name: eureka
   profiles:
      active: dev
